site_name: Gravinium Wiki
site_url: https://wiki.gravinium.org
repo_name: Gravinium-VR/Public
repo_url: https://github.com/Gravinium-VR/Public
edit_uri: edit/main/docs/

# Extensions/Plugins
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

plugins:
  - search
  - meta
  - awesome-nav

# Theme/Page Setup
theme:
  name: material
  custom_dir: overrides
  font:
    code: JetBrains Mono
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: purple
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.indexes
    - navigation.prune 
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - toc.integrate
    - toc.follow

# Other
extra:
  social:
    - icon: simple/discord
      link: https://gravinium.org/discord
    - icon: simple/twitch
      link: https://gravinium.org/twitch
    - icon: simple/youtube
      link: https://gravinium.org/youtube
    - icon: simple/bluesky
      link: https://gravinium.org/bluesky
    - icon: simple/x
      link: https://gravinium.org/x
    - icon: simple/instagram
      link: https://gravinium.org/instagram
    - icon: simple/tiktok
      link: https://gravinium.org/tiktok

copyright: Content licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">CC BY-SA 4.0</a> unless specified otherwise.